### ISSUE TITLE
Rethinking Variables in CSS

### ISSUE THREAD

**Issue by avishnyak** [jxnblk/blog#33]
This breaks down when you do a site update and you want your primary color to be blue instead of `.green`.  Do you modify your CSS to make `.green = blue` or do you go around changing every style?

No, you would say the color should be called .primary or something like that which is exactly where Bootstrap and other frameworks ended up.  That's why they have `.button .button-primary` as a typical style.  The problems of course pile up when you need styles that have to make assumptions about certain DOM hierarchies.  For example, you want a badge that floats right.  That means it must be inside of a block element to work.  This leads to the div-itis that bootstrap has become with a bunch of classes that you have to remember to put together in a certain order (`.btn` before `.btn-default`) but not on the same element as `.float-right` because that will mess with the text inside.

Just some thoughts...

**Comment by jxnblk** [comment]
Well to be honest, I've never worked for a company that's changed their primary brand color from blue to green, but if that's an issue for you, you could certainly abstract the name out to something like `primary` if you wanted to.

I'm not sure I follow what you're suggesting towards the end, but the amount of _div-itis_ I've seen in real code bases pales in comparison to the messes I've seen caused by CSS and extensive use of preprocessors. And when I see the `right` class used in markup, I tend to see the context in which it's being used.
